# Generated by Django 5.1b1 on 2024-07-03 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "token",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="token"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"is_staff": False},
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="users",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(choices=[("", "")], verbose_name="language"),
                ),
                (
                    "domain",
                    models.CharField(
                        default="django", max_length=20, verbose_name="domain"
                    ),
                ),
                ("pofile", models.TextField(verbose_name="pofile")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogs",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalog",
                "verbose_name_plural": "catalogs",
            },
        ),
    ]
