# Generated by Django 5.1b1 on 2024-07-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalog",
            options={
                "ordering": ["language_code", "domain"],
                "verbose_name": "catalog",
                "verbose_name_plural": "catalogs",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="token",
            field=models.CharField(
                editable=False, max_length=100, unique=True, verbose_name="token"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catalog",
            unique_together={("project", "language_code", "domain")},
        ),
    ]
