# Generated by Django 5.1b1 on 2024-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_catalog_created_at_catalog_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="_email_domains",
            field=models.TextField(
                blank=True,
                help_text="User accounts on these domains will automatically get access to this project. One domain per line.",
                verbose_name="email domains",
            ),
        ),
    ]
