# Generated by Django 5.1b1 on 2024-07-05 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="token",
        ),
    ]
