/* eslint-disable */
gettext("Cancel")
gettext("delete your progress")
gettext("delete")
gettext("Do you want to interrupt the task?")
gettext("edit")
gettext("home")
gettext("I am sure that I want to delete my progress and not continue later.")
gettext("I want to take a break and have written down the code.")
gettext("pause")
gettext("Save current state")
gettext("Would you like to continue later?")
gettext("Would you like to delete your progress.")
gettext("You can also switch to another device.")
gettext("You can continue later with this code.")
gettext("You will receive a code to continue at any time.")
